# Generated by Django 5.2.8 on 2026-03-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='Новостройка'),
        ),
    ]
