# Generated by Django 5.2.8 on 2026-03-15 12:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_pure_phone_alter_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
