# Generated by Django 5.2.8 on 2026-03-22 12:10

from django.db import migrations, models

def migrate_owners(apps,schema_editor):
    Flat = apps.get_model('property',"Flat")
    Owner = apps.get_model('property','Owner')

    flat_objects = Flat.objects.all()

    for flat_object in flat_objects:
        Owner.objects.get_or_create(owner=flat_object.owner, owners_phonenumber=flat_object.owners_phonenumber, owner_pure_phone=flat_object.owner_pure_phone, defaults={"owners_phonenumber": None, "owner_pure_phone": None})

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
