# Generated by Django 5.2.8 on 2026-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20260322_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='flats', to='property.owner'),
        ),
    ]
