# Generated by Django 5.2.8 on 2026-03-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_owner_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners',
        ),
    ]
