# Generated by Django 5.2.8 on 2026-03-29 11:50

from django.db import migrations

def bundle_flats_to_owner(apps,schema_editor):
    Flat = apps.get_model('property',"Flat")
    Owner = apps.get_model('property','Owner')

    owner_objects = Owner.objects.all()

    for owner_object in owner_objects.iterator():
        owner_object.owner_flats.set(Flat.objects.filter(owner=owner_object.owner))

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property','Owner')
    Owner.objects.all().update(owner_flats=[])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_owner_owners'),
    ]

    operations = [
        migrations.RunPython(bundle_flats_to_owner, move_backward),
    ]
